@startuml
left to right direction
actor "Cliente" as cliente
actor "Administrador" as administrador
rectangle Aplicação-Lava-Rápido {
  usecase "Login/logout" as login
  usecase "Cadastro" as cadastro
  usecase "Recuperação de Senha" as recuperacao
  usecase "Agendar serviço" as agendamento
  usecase "Cancelar Agendamento" as cancelarAgendamento
  usecase "Cadastrar veiculos" as veiculos
  usecase "Consultar Serviços" as consultarServicos
  usecase "Alterar Agendamento" as alterarAgendamento
  usecase "Consultar Agendamentos" as consultarAgendamentos
  usecase "Consultar Clientes" as consultarClientes
  usecase "Cadastrar cartão" as cartoes



}

cliente --> login
cliente --> cadastro
cliente --> agendamento
cliente --> alterarAgendamento
cliente --> cancelarAgendamento
cliente --> recuperacao
cliente --> cancelarAgendamento
cliente --> consultarServicos
cliente --> consultarAgendamentos
cliente --> veiculos
cliente --> cartoes

administrador --> consultarAgendamentos
administrador --> consultarClientes
administrador --> cancelarAgendamento
administrador --> login
@enduml